title = "Experimental configs for Bilateral Stamping"

[longtime]
model_name = "Unisoma"
description = "Longtime Task on Bilateral Stamping"
version = "250526_1"

assets_root = "./root_folder/bilateral_stamping/assets"
data_root = "./root_folder/bilateral_stamping/data"


[longtime.hyperparameter]
seed = 42
lr = 3e-4
lr_decay = 10
epochs = 100
weight_decay = 1e-5
batch_size = 1
eval_per_epoch = 1
device = "cuda:0"
criterion = "relative l2"


[longtime.unisoma]
emb_dim = 128
slice_num = 32
use_edge = true
k = 3
load_dim = 6
rigid_dim = 3
input_deformable_dim = 3
output_deformable_dim = 5
load_num = 2
rigid_num = 2
deformable_num = 2
contact_id = [
    [0, 1],
    [0, 2],
    [0, 3],
    [1, 2],
    [1, 3]
]
processor_num = 2
attention_heads_num = 8
mlp_ratio = 4
dropout = 0
bias = false
act = "gelu"